name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: Test backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name:   
        uses: pnpm/action-setup@v4
        with:
          version: 10
      
      - name: ğŸ”¨ Installing dependencies
        run: make install

      - name: ğŸ” Running tests
        run: make test
        
      - name: Ensure badges branch exists
        run: |
          if ! git ls-remote --exit-code origin badges; then
            git checkout --orphan badges
            git reset --hard
            git commit --allow-empty -m "init badges branch"
            git push origin badges
            git checkout main
          fi

      - name: âš™ï¸ Generating coverage badges
        uses: jpb06/coverage-badges-action@latest
        with:
          target-branch: badges
          output-folder: ./docs/badges
          coverage-summary-path: |
            ./src/auth-server/**/coverage/coverage-summary.json