name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: Test backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name:   
        uses: pnpm/action-setup@v4
        with:
          version: 10
      
      - name: ğŸ”¨ Installing dependencies
        run: make install

      # - name: Delete 'badges' branch
      #   run: git push origin --delete badges

      - name: Create badges branch
        run: git checkout -b badges

      - name: ğŸ” Running tests
        run: make test

      - name: âš™ï¸ Generating coverage badges
        uses: jpb06/coverage-badges-action@latest
        with:
          target-branch: badges
          output-folder: ./docs/badges
          coverage-summary-path: |
            ./src/auth-server/**/coverage/coverage-summary.json
            
      # - name: â¬†ï¸ Push badges
      #   run: git push origin badges